### PR TITLE
Display info about total count of catched LRR

### PR DESCRIPTION
**Pull request by keul**
From:

```
Stats from 2016-06-06 00:07:00 to 2016-06-06 18:18:17
```

...to...

```
Stats from 2016-06-06 00:07:00 to 2016-06-06 18:18:17 (347 LRR catched)
```

### CODE REVIEW

**Comment by cekk** [comment]
Thanks @keul!
You can release it on pypi when you wants..i don't have that power :(

**Comment by keul** [comment]
@cekk d'oh!! 😄 

Shared on pypi!

Thanks

**Comment by keul** [comment]
BTW I can't release because I've no write access there to perform a "fullrelease".

**Comment by cekk** [comment]
@keul d'oh!! (cit.)

ok, released

**Pull request merged**
